org.gradle.java.home=E:/JDK25
org.gradle.parallel=false
loom.mixin.useLegacyMixinAp=true

# Mod Properties
mod_name=Speedometer
mod_version=1.2.3-26.2
maven_group=net.vanillaoutsider
archives_base_name=speedometer

# Dependencies
minecraft_version=26.2
parchment_minecraft_version=26.2
parchment_version=2026.01.22

# Fabric Loader and API Configuration
fabric_version=0.150.1+26.2
fabric_loader_version=0.19.1

# Loom
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true
