org.gradle.parallel=true
org.gradle.java.home=E:/JDK25

# Mod Properties
mod_name=Speedometer
mod_version=1.2.13+1.21.11
maven_group=net.dasik.speedometer
archives_base_name=speedometer

# Dependencies
minecraft_version=1.21.11
fabric_loader_version=0.19.3
fabric_version=0.141.6+1.21.11

# Loom
fabric.loom.suppressJavaCompatibilityChecks=true
loom.suppressJavaCompatibilityChecks=true

# DasikLibrary
dasik_library_version=1.1.0+1.21.11
